### ISSUE TITLE
Add ping command 

### ISSUE THREAD

**Issue by galaxyhdm** [Dev-Gruppe/FunDiscordBot#6]
A command to check the latency of the bot

**Comment by michivip** [comment]
The basic PingCommand was added to the bot with the commit https://github.com/Dev-Gruppe/FunDiscordBot/commit/9133ed624060d71ac9bd5b700638af55c615b71d in the developer branch.

**Comment by michivip** [comment]
Merged into the master branch with commit https://github.com/Dev-Gruppe/FunDiscordBot/commit/9133ed624060d71ac9bd5b700638af55c615b71d.

**Comment by michivip** [comment]
Merged into the master branch with commit https://github.com/Dev-Gruppe/FunDiscordBot/commit/9133ed624060d71ac9bd5b700638af55c615b71d.
